# Generated by Django 3.1.7 on 2021-04-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Obshaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Общежитие')),
            ],
            options={
                'verbose_name': 'Общежитие',
                'verbose_name_plural': 'Общежитии',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статус',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Тип документа',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komnata', models.IntegerField(db_index=True, verbose_name='Комната')),
                ('fio', models.CharField(max_length=150, unique=True, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('zahislenie', models.DateTimeField(verbose_name='Зачисление')),
                ('uhod', models.DateTimeField(verbose_name='Уход')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('facult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.facult', verbose_name='Факультет')),
                ('obshaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.obshaga', verbose_name='Общежитие')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Жители',
                'verbose_name_plural': 'Жители',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата приема')),
                ('file', models.FileField(upload_to='', verbose_name='Документ')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.people', verbose_name='Житель')),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.tip', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Перечень документов',
                'verbose_name_plural': 'Перечень документов',
            },
        ),
    ]
